config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }
  devise_for :developers, controllers: {
    sessions: 'developers/sessions'
  }
  mount RailsAdmin::Engine => '/developer', as: 'rails_admin'

  # Publicページ
  get  '/', :to => redirect('/ios-app')
  get  '/', :to => redirect('/press')

  # 旧STYLER MAGからのリダイレクト処理
  get  '/wp_articles/:id'              => 'articles#wp_show'

  # 旧URLからのリダイレクト処理
  get  '/replys/:id'                   => 'replies#ex_show'

  resources :articles, only: %i(index show)
  resources :comments, only: %i(create destroy)
  resources :conversations, only: %i(index new show)
  resources :events
  resources :favorites, only: %i(create destroy)
  resources :feedbacks, only: %i(new create)
  resources :follows, only: %i(create destroy)
  resources :interests, only: %i(create destroy)
  resources :items
  resources :likes, only: %i(create destroy)
  resources :messages, only: %i(create)
  resources :notifications, only: %i(index)
  resources :posts do
    collection do
      get :latest
      get :unreplied
    end
  end
  resources :replies, except: %i(index destroy)
  get  '/replies/:id/embed'            => 'replies#embed', as: 'replies_embed'
  get  '/replies/:id/embed_link'       => 'replies#generate_embed_link', as: 'embed_link'
  resources :reports, only: %i(new create)
  resources :shops, except: %i(new create destroy) do
    member do
      get :items
      get :events
      get :staffs
      get :information
    end
  end
  resources :shop_registrations, only: %i(new create)
  resources :shop_users, only: %i(new create)
  resources :tops, only: %i(), path: '/' do
    collection do
      get :privacy_policy
      get :use_policy
      get :company
      get :help
      get :pending
    end
  end
  resources :users, only: %i(show edit update) do
    member do
      get :watches
      get :likes
      get :interests
      get :follows
      get :followers
    end
    collection do
      get :setting
      get :change_email
      get :mail_setting
    end
  end
  resources :watches, only: %i(create destroy)

  namespace :admin do
    resources :articles, only: %i(index edit update) do
      get :reload, on: :collection
    end
    resources :authors, only: %i(index edit update)
    resources :categories, only: %i(index new create)
    resources :contacts, only: %i(index new create)
    resources :kpis, only: %i(index)
    resources :html_mails, only: %i(index) do
      collection do
        get :welcome_mail
        get :comment_mail
        get :feedback_mail
        get :message_mail
        get :reply_mail
        get :start_events_mail
        get :approval_mail
        get :staff_invite_mail
      end
    end
    resources :push_notifications, only: %i(new create)
    resources :reports, only: %i(index update)
    resources :shops, only: %i(index new create update)
    resources :shop_registrations, only: %i(index show update)
    resources :tops, only: %i(index)
    resources :users, only: %i(index new create)
  end

  namespace :api, { format: 'json' } do
    # KPI
    get    '/kpi'                               => 'tops#kpi'

    # 削除予定
    get    '/articles_top'                      => 'articles#top'
    get    '/features'                          => 'articles#feature'
    get    '/future_events'                     => 'events#future'
    get    '/ongoing_events'                    => 'events#ongoing'
    get    '/latest_posts'                      => 'posts#latest'
    get    '/unreplied_posts'                   => 'posts#unreplied'

    # ios
    resources :articles, only: %i(index show) do
      get :top, on: :collection
    end
    resources :categories, only: %i(index) do
      get :articles, on: :member
    end
    resources :comments, only: %i(create destroy)
    resources :conversations, only: %i(index) do
      get :messages, on: :member
    end
    resources :events, except: %i(new edit)
    resources :feedbacks, only: %i(create)
    resources :follows, only: %i(create destroy)
    resources :interests, only: %i(create destroy)
    resources :items, only: %i(index show update)
    resources :likes, only: %i(create destroy)
    resources :messages, only: %i(index create)
    resources :notifications, only: %i(index)
    resources :posts, except: %i(new edit) do
      member do
        get :replies
        get :comments
      end
      get :unreplied, on: :collection
    end
    resources :replies, only: %i(create show update)
    resources :reports, only: %i(create)
    resources :shops, only: %i(index show update) do
      member do
        get :items
        get :events
        get :staffs
      end
    end
    resources :tags, only: %i(index) do
      get :articles, on: :member
    end
    resources :tops, only: %i(), path: '/' do
      collection do
        get  :check_version
        post :login
        post :sign_up
        post :facebook
        get  :token_reference
        get  :check_notifications
        get  :coupons
      end
    end
    resources :users, only: %i(show) do
      member do
        get :likes
        get :interests
        get :posts
        get :watches
        get :follows
        get :replies
        get :followers
      end
      collection do
        patch :profile
        patch :setting
        patch :email
        patch :password
      end
    end
    resources :watches, only: %i(create destroy)
  end

  namespace :dashboard, { format: 'json' } do
    resources :tops, only: %i(), path: '/' do
      collection do
        post :login
        get  :shop_stats
        get  :overall_stats
        get  :shop_staffs
        get  :shop_replies
      end
    end
  end
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < Admin::AdminController
  def index
    @objects_count = Shop.count
    @shops = Shop.all.page(page_params[:page]).per(50)
  end

  def new
  end

  def create
    if shop_params[:name].present?
      shop = Shop.where(shop_params).first_or_create
      if shop.persisted?
        Image.create_by_object(shop, image_params[:photo])
        redirect_to admin_shops_path, notice: 'ショップを作成しました'
      else
        redirect_to new_admin_shop_path, alert: 'ショップを作成出来ません'
      end
    else
      redirect_to new_admin_shop_path, alert: 'ショップ名を記入してください'
    end
  end

  def update
    shop = Shop.find_by(id: id_params[:id])
    if shop
      if shop.closed
        shop.update(closed: false)
        redirect_to admin_shops_path, notice: 'ショップの非表示を解除しました'
      else
        shop.update(closed: true)
        redirect_to admin_shops_path, notice: 'ショップを非表示にしました'
      end
    else
      redirect_to admin_shops_path, alert: 'リクエストを処理出来ません'
    end
  end

  private
  def id_params
    params.permit(:id)
  end

  def image_params
    params.permit(:photo)
  end

  def page_params
    params.permit(:page)
  end

  def shop_params
    params.permit(:name, :address, :tel, :website, :profile)
  end
end

app/controllers/api/shops_controller.rb
class Api::ShopsController < Api::ApiController
  skip_before_action :check_token, except: %i(update)

  def index
    if location_params[:location]
      if order_params[:order] == 'name'
        @shops = Shop.api_index_alphabetical(last_shop).by_location(location_params[:location])
      else
        @shops = Shop.api_index(last_shop).by_location(location_params[:location])
      end
    else
      @locations = Settings.prefecture
    end
    render template: 'api/shops/index'
  end

  def show
    @shop = Shop.cached_find_by_id(id_params[:id], 60.minutes)
    if @shop
      render template: 'api/shops/show'
    else
      render json: {message: 'ショップが見つかりません'}, status: 404
    end
  end

  def items
    shop = Shop.cached_find_by_id(id_params[:id], 60.minutes)
    if shop
      if category_params[:category_id]
        category = Category.find_by(id: category_params[:category_id])
        if category
          @items = shop.items.by_category(category.id).api_index(last_item)
          render template: 'api/items/index'
        else
          render json: {message: 'カテゴリーが見つかりません'}, status: 404
        end
      else
        @items = shop.items.api_index(last_item)
        render template: 'api/items/index'
      end
    else
      render json: {message: 'ショップが見つかりません'}, status: 404
    end
  end

  def events
    shop = Shop.cached_find_by_id(id_params[:id], 60.minutes)
    if shop
      @events = shop.events.api_index(last_event)
      render template: 'api/events/index'
    else
      render json: {message: 'ショップが見つかりません'}, status: 404
    end
  end

  def staffs
    shop = Shop.cached_find_by_id(id_params[:id], 60.minutes)
    if shop
      @users = shop.users.api_index(last_user)
      render template: 'api/users/index'
    else
      render json: {message: 'ショップが見つかりません'}, status: 404
    end
  end

  def update
    @shop = Shop.find_by(id: id_params[:id])
    if @shop
      if @shop == @current_user.try(:shop)
        @shop.update(name_params) if name_params[:name].present?
        @shop.update(detail_params)
        Image.create_by_object(@shop, image_params[:photo])
        render template: 'api/shops/show'
      else
        render json: {message: 'ショップの編集権限がありませんr'}, status: 401
      end
    else
      render json: {message: 'ショップが見つかりません'}, status: 404
    end
  end

  private
  def last_shop
    Shop.find(last_params[:last_object_id]) if last_params[:last_object_id].present?
  end

  def last_item
    Item.find(last_params[:last_object_id]) if last_params[:last_object_id].present?
  end

  def last_event
    Event.find(last_params[:last_object_id]) if last_params[:last_object_id].present?
  end

  def last_user
    User.find(last_params[:last_object_id]) if last_params[:last_object_id].present?
  end

  def last_params
    params.permit(:last_object_id)
  end

  def category_params
    params.permit(:category_id)
  end

  def detail_params
    params.permit(:profile, :address, :tel, :website, :business_hours, :location, :station)
  end

  def id_params
    params.permit(:id)
  end

  def image_params
    params.permit(:photo)
  end

  def location_params
    params.permit(:location)
  end

  def name_params
    params.permit(:name)
  end

  def order_params
    params.permit(:order)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  skip_before_action :authenticate_user!, except: %i(edit update)

  def index
    # activity_id = 21
    # log_activity(current_user, activity_id, @platform)

    if location_params[:location]
      if order_params[:order] == 'name'
        @shops = Shop.web_index_alphabetical(page_params[:page]).by_location(location_params[:location])
      else
        @shops = Shop.web_index(page_params[:page]).by_location(location_params[:location])
      end
    else
      @locations = Settings.prefecture
    end
  end

  def show
    @shop = Shop.cached_find_by_id(id_params[:id], 60.minutes)
    if @shop
      @replies = @shop.replies.web_index(page_params[:page])
    else
      redirect_to root_path, alert: 'ショップが見つかりません'
    end
  end

  def items
    @shop = Shop.cached_find_by_id(id_params[:id], 60.minutes)
    if @shop
      @items = shop.items.web_index(page_params[:page])
    else
      redirect_to root_path, alert: 'ショップが見つかりません'
    end

    render raw: render_query_to_string_with_cache(@events, 60.minutes)
  end

  def events
    @shop = Shop.cached_find_by_id(id_params[:id], 60.minutes)
    if @shop
      @events = @shop.events.web_index(page_params[:page])
    else
      redirect_to root_path, alert: 'ショップが見つかりません'
    end

    render raw: render_query_to_string_with_cache(@events, 60.minutes)
  end

  def staffs
    @shop = Shop.cached_find_by_id(id_params[:id], 60.minutes)
    if @shop
      @staffs = @shop.users.web_index(page_params[:page])
    else
      redirect_to root_path, alert: 'ショップが見つかりません'
    end

    render raw: render_query_to_string_with_cache(@staffs, 60.minutes)
  end

  def information
    @shop = Shop.cached_find_by_id(id_params[:id], 60.minutes)
    redirect_to root_path, alert: 'ショップが見つかりません' unless @shop
  end

  def edit
    @shop = Shop.cached_find_by_id(id_params[:id], 60.minutes)
    if @shop
      unless @shop == current_user.shop
        redirect_to root_path, alert: 'ショップ情報の編集権限がありません'
      end
    else
      redirect_to root_path, alert: 'ショップが見つかりません'
    end
  end

  def update
    shop = Shop.find_by(id: id_params[:id])
    if shop
      if shop == current_user.shop
        shop.update(name_params) if name_params[:name].present?
        shop.update(detail_params)
        Image.create_by_object(shop, image_params[:photo])
        redirect_to shop_path(shop), notice: 'ショップ情報を編集しました'
      else
        redirect_to root_path, alert: 'ショップ情報の編集権限がありません'
      end
    else
      redirect_to root_path, alert: 'ショップが見つかりません'
    end
  end

  private
  def detail_params
    params.permit(:profile, :address, :tel, :website, :business_hours)
  end

  def id_params
    params.permit(:id)
  end

  def image_params
    params.permit(:photo)
  end

  def location_params
    params.permit(:location)
  end

  def name_params
    params.permit(:name)
  end

  def order_params
    params.permit(:order)
  end

  def page_params
    params.permit(:page)
  end
end

app/views/shops/_shop_list.html.erb
<% shops.each do |shop| %>

  <article class="p-article p-article-shop-list u-paper-shadow-z1">
    <%= link_to shop_path(shop), class: "p-article-owner" do %>
      <div class="c-user-name c-shop-name">
        <%= image_tag(object_image(shop),class: "c-img-shop-profile", size: "70x70") %>
        <h4>
          <%= shop.name %>
          <span><%= shop.address if shop.address.present? %></span>
        </h4>
      </div>
    <% end %>
  </article>

<% end %>

app/views/shops/_shop_stats.html.erb
<div class="p-article-stats">
  <%= link_to shop_path(@shop) do %><%= @shop.replies.count %><span>Replies</span><% end %>
  <%= link_to events_shop_path(@shop) do %><%= @shop.events.count %><span>Events</span><% end %>
  <%= link_to staffs_shop_path(@shop) do %><%= @shop.users.count %><span>Staffs</span><% end %>
</div>

app/views/shops/_tab.html.erb
<div class="p-header-tab">
  <%= link_to "Reply", shop_path(@shop), class: "c-header-tab #{'is-current' if controller.action_name == 'show'}" %>
  <%= link_to "Event", events_shop_path, class: "c-header-tab #{'is-current' if controller.action_name == 'events'}" %>
  <%= link_to "Staff", staffs_shop_path, class: "c-header-tab #{'is-current' if controller.action_name == 'staffs'}" %>
</div>

app/views/shops/edit.html.erb
<section class="l-flex__center">
  <%= form_tag(shop_path, multipart: true, method: "patch", class: "p-create-form u-paper-shadow-z1") do %>
    <h3>ショップ情報編集</h3>
    <div class="c-photo-uploader u-user-avatar">
      <%= image_tag(object_image(@shop)) %>
      <%= file_field_tag :photo, 
                         class: "u-photo-uploader", 
                         accept: "image/jpeg,image/png,image/gif" %>
    </div>
    <ul>
      <li>
        <label for="name">ショップ名：<span class="c-icon-requirement"><i class="path1"></i><i class="path2"></i></span></label>
        <input type="text" name="name" id="name" value="<%= @shop.name %>" placeholder="例：STYLER 原宿店" required aria-required="true" class="c-form__textarea">
      </li>
      <li>
        <label for="address">ショップ所在地：</label>
        <%= render partial: 'users/location', locals: {location: @shop.location} %>
        <input type="text" name="address" id="address" value="<%= @shop.address %>" placeholder="例：渋谷区神南1-10-6" class="c-form__textarea" style="margin:10px 0px;">
      </li>
      <li>
        <label for="tel">電話番号：</label>
        <input type="tel" name="tel" id="tel" value="<%= @shop.tel %>" placeholder="例：0312345678" class="c-form__textarea">
      </li>
      <li>
        <label for="website">Webサイト：</label>
        <input type="url" name="website" id="website" value="<%= @shop.website %>" placeholder="例：http://styler.link/" class="c-form__textarea">
      </li>
      <li>
        <label for="business_hours">営業時間：</label>
        <input type="text" name="business_hours" id="business_hours" value="<%= @shop.business_hours %>" placeholder="例：平日 12:00～20:00 / 土・日・祝 11:00～20:00" class="c-form__textarea">
      </li>
      <li>
        <label for="profile">ショップ紹介：</label>
        <%= text_area_tag "profile", @shop.profile, 
                          rows: "3", 
                          placeholder: "例：主にメンズファッションを取り扱っています。", 
                          class: "c-form__textarea", 
                          id: "textarea" %>
      </li>
    </ul>
    <%= button_tag "更新する", type: 'submit', class: "c-button__submit", data: { disable_with: "送信中…" } %>
    <%= button_tag "キャンセル", type: 'button', class: "c-button__cancel", onClick: "history.back()" %>
  <% end %>
</section>

app/views/shops/events.html.erb
<section class="l-flex__center has-header-tab">

  <article class="p-article p-article-profile">
    <div class="p-article-owner">
      <div class="c-user-name u-shop-avatar">
        <%= image_tag(object_image(@shop), size: "120x120") %>
        <h4>
          <%= @shop.name %>
          <span><i><%= @shop.address %></i></span>
          <%= link_to "このショップ詳細 >", information_shop_path(@shop) %>
        </h4>
      </div>
      <%= link_to "", edit_shop_path(@shop), class: "c-user-action c-icon-setting" if current_user.try(:staff?) && @shop == current_user.shop %>
    </div>

    <%= render "shop_stats" %>
  </article>

  <div id="shop-content">
    <% if @events.present? %>
      <% @events.each do |event| %>
        <article class="p-article p-article-event u-paper-shadow-z1">
          <%= link_to event_path(event), class: "p-article-img" do %>
            <div class="c-event-img" style="background-image:url('<%= image_url(object_image(event, 'rectangle')) %>');"></div>
            <div class="c-event-header">
              <% if event.created_at > 1.week.ago %>
                <p class="c-icon-new">新着</p>
              <% end %>
              <h2><%= event.title %></h2>
              <span><%= event.start_date %> ~ <%= event.finish_date.presence %></span>
              <span><%= event.location %></span>
              <div class="c-user-name">
                <%= image_tag(object_image(event.shop), size: "32x32") %>
                <h4><%= event.shop.name %></h4>
              </div>
            </div>
          <% end %>
        </article>
      <% end %>
    <% else %>
      <article class="p-article u-paper-shadow-z1">
        <p class="u-text-align__center">まだ Event がありません</p>
      </article>
    <% end %>
  </div>

  <%= form_tag events_shop_path, method: "get", id: "pagination" do %>
    <%= link_to_next_page @events, "", remote: true %>
  <% end %>

</section>

<% if current_user.try(:staff?) && @shop == current_user.shop %>
  <div class="c-button__event u-scrolled-animation u-paper-shadow-button">
    <%= link_to new_event_path, class: "c-user-name" do %>
      <span class="c-icon-event"></span>
      <h4>
        新しいイベントを作成する
      </h4>
    <% end %>
  </div>
<% end %>

app/views/shops/index.html.erb
<section class="l-flex__center">
  <div id="shop-list">
    <%= render partial: "shops/shop_list", locals: { shops: @shops } %>
  </div>
  
  <%= form_tag shops_path, method: "get", id: "pagination" do %>
    <%= link_to_next_page @shops, "", remote: true %>
  <% end %>
</section>

app/views/shops/index.js.erb
$("#shop-list").html("<%= escape_javascript(render partial: 'shops/shop_list', locals: { shops: @shops } ) %>");
$('#pagination').html('<%= escape_javascript(link_to_next_page @shops, "", remote: true) %>');

app/views/shops/information.html.erb
<section class="l-flex__center">

  <article class="p-article p-article-profile">
    <div class="p-article-owner">
      <div class="c-user-name u-shop-avatar">
        <%= image_tag(object_image(@shop), size: "120x120") %>
        <h4>
          <%= link_to "< ショップページに戻る", shop_path(@shop), style: "margin-bottom:10px;" %>
          <%= @shop.name %>
        </h4>
      </div>
      <%= link_to "", edit_shop_path(@shop), class: "c-user-action c-icon-setting" if current_user.try(:staff?) && @shop == current_user.shop %>
    </div>
  </article>

  <article class="p-article u-paper-shadow-z1">
    <div class="p-article-desc">
      <h4>ショップ紹介</h4>
      <%= @shop.profile %>
    </div>
    <div class="p-article-shop-info">
      <ul>
        <% if @shop.address.present? %>
          <li>
            <div><span>ショップ所在地：</span><h5><%= @shop.address %></h5></div>
            <%= link_to "<i class=\"c-icon-map\"></i>".html_safe, "https://maps.google.com/maps?q=#{@shop.address}", :class => "c-icon-button", target: "_blank" %></li>
        <% end %>
        <% if @shop.tel.present? %>
          <li>
            <div><span>電話番号：</span><h5><%= @shop.tel %></h5></div>
            <%= link_to "<i class=\"c-icon-phone\"></i>".html_safe, "tel:#{@shop.tel}", :class => "c-icon-button" %>
          </li>
        <% end %>
        <% if @shop.website.present? %>
          <li>
            <div><span>ホームページURL：</span><h5><%= @shop.website %></h5></div>
            <%= link_to "<i class=\"c-icon-browser\"></i>".html_safe, "#{@shop.website}", :class => "c-icon-button", target: "_blank" %>
          </li>
        <% end %>
        <% if @shop.business_hours.present? %>
          <li>
            <div><span>営業時間：</span><h5><%= @shop.business_hours %></h5></div>
          </li>
        <% end %>
      </ul>
    </div>
  </article>

</section>

app/views/shops/show.html.erb
<section class="l-flex__center has-header-tab">

  <article class="p-article p-article-profile">
    <div class="p-article-owner">
      <div class="c-user-name u-shop-avatar">
        <%= image_tag(object_image(@shop), size: "120x120") %>
        <h4>
          <%= @shop.name %>
          <span><i><%= @shop.address %></i></span>
          <%= link_to "このショップ詳細 >", information_shop_path(@shop) %>
        </h4>
      </div>
      <%= link_to "", edit_shop_path(@shop), class: "c-user-action c-icon-setting" if current_user.try(:staff?) && @shop == current_user.shop %>
    </div>

    <%= render "shop_stats" %>
  </article>

  <div id="shop-content">
    <% if @replies.present? %>
      <article class="p-article p-article-post u-paper-shadow-z1">
        <div class="p-article-img" style="margin-top:0;">
          <% @replies.each do |reply| %>
            <%= link_to reply_path(reply, anchor: "reply"), data: { no_turbolink: true } do %>
              <%= image_tag(object_image(reply)) %>
            <% end %>
          <% end %>
        </div>
      </article>
    <% else %>
      <article class="p-article u-paper-shadow-z1">
        <p class="u-text-align__center">まだ Reply がありません</p>
      </article>
    <% end %>
  </div>

  <%= form_tag shop_path(@shop), method: "get", id: "pagination" do %>
    <%= link_to_next_page @replies, "", remote: true %>
  <% end %>

</section>

app/views/shops/show.js.erb
<% if params[:ajax_handler] === 'reply' %>
  $("#shop-content").html("<%= escape_javascript(render 'reply', object: @replies) %>");
<% elsif params[:ajax_handler] === 'events' %>
  $("#shop-content").html("<%= escape_javascript(render 'event', object: @events) %>");
<% elsif params[:ajax_handler] === 'staff' %>
  $("#shop-content").html("<%= escape_javascript(render 'staff', object: @staffs) %>");
<% end %>

app/views/shops/staffs.html.erb
<section class="l-flex__center has-header-tab">

  <article class="p-article p-article-profile">
    <div class="p-article-owner">
      <div class="c-user-name u-shop-avatar">
        <%= image_tag(object_image(@shop), size: "120x120") %>
        <h4>
          <%= @shop.name %>
          <span><i><%= @shop.address %></i></span>
          <%= link_to "このショップ詳細 >", information_shop_path(@shop) %>
        </h4>
      </div>
      <%= link_to "", edit_shop_path(@shop), class: "c-user-action c-icon-setting" if current_user.try(:staff?) && @shop == current_user.shop %>
    </div>

    <%= render "shop_stats" %>
  </article>

  <div id="shop-content">
    <% if @staffs.present? %>
      <article class="p-article p-article-staff u-paper-shadow-z1">
        <% @staffs.each do |staff| %>
          <%= link_to user_path(staff), class: "p-article-owner" do %>
            <div class="c-user-name">
              <%= image_tag(object_image(staff), size: "64x64") %>
              <h4>
                <%= staff.name %>
              </h4>
            </div>
          <% end %>
        <% end %>
      </article>
    <% else %>
      <article class="p-article u-paper-shadow-z1">
        <p class="u-text-align__center">まだ他のスタッフはいません</p>
      </article>
    <% end %>
  </div>

  <%= form_tag staffs_shop_path, method: "get", id: "pagination" do %>
    <%= link_to_next_page @staffs, "", remote: true %>
  <% end %>

</section>