config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }
  devise_for :developers, controllers: {
    sessions: 'developers/sessions'
  }
  mount RailsAdmin::Engine => '/developer', as: 'rails_admin'

  # Publicページ
  get  '/', :to => redirect('/ios-app')
  get  '/', :to => redirect('/press')

  # 旧STYLER MAGからのリダイレクト処理
  get  '/wp_articles/:id'              => 'articles#wp_show'

  # 旧URLからのリダイレクト処理
  get  '/replys/:id'                   => 'replies#ex_show'

  resources :articles, only: %i(index show)
  resources :comments, only: %i(create destroy)
  resources :conversations, only: %i(index new show)
  resources :events
  resources :favorites, only: %i(create destroy)
  resources :feedbacks, only: %i(new create)
  resources :follows, only: %i(create destroy)
  resources :interests, only: %i(create destroy)
  resources :items
  resources :likes, only: %i(create destroy)
  resources :messages, only: %i(create)
  resources :notifications, only: %i(index)
  resources :posts do
    collection do
      get :latest
      get :unreplied
    end
  end
  resources :replies, except: %i(index destroy)
  get  '/replies/:id/embed'            => 'replies#embed', as: 'replies_embed'
  get  '/replies/:id/embed_link'       => 'replies#generate_embed_link', as: 'embed_link'
  resources :reports, only: %i(new create)
  resources :shops, except: %i(new create destroy) do
    member do
      get :items
      get :events
      get :staffs
      get :information
    end
  end
  resources :shop_registrations, only: %i(new create)
  resources :shop_users, only: %i(new create)
  resources :tops, only: %i(), path: '/' do
    collection do
      get :privacy_policy
      get :use_policy
      get :company
      get :help
      get :pending
    end
  end
  resources :users, only: %i(show edit update) do
    member do
      get :watches
      get :likes
      get :interests
      get :follows
      get :followers
    end
    collection do
      get :setting
      get :change_email
      get :mail_setting
    end
  end
  resources :watches, only: %i(create destroy)

  namespace :admin do
    resources :articles, only: %i(index edit update) do
      get :reload, on: :collection
    end
    resources :authors, only: %i(index edit update)
    resources :categories, only: %i(index new create)
    resources :contacts, only: %i(index new create)
    resources :kpis, only: %i(index)
    resources :html_mails, only: %i(index) do
      collection do
        get :welcome_mail
        get :comment_mail
        get :feedback_mail
        get :message_mail
        get :reply_mail
        get :start_events_mail
        get :approval_mail
        get :staff_invite_mail
      end
    end
    resources :push_notifications, only: %i(new create)
    resources :reports, only: %i(index update)
    resources :shops, only: %i(index new create update)
    resources :shop_registrations, only: %i(index show update)
    resources :tops, only: %i(index)
    resources :users, only: %i(index new create)
  end

  namespace :api, { format: 'json' } do
    # KPI
    get    '/kpi'                               => 'tops#kpi'

    # 削除予定
    get    '/articles_top'                      => 'articles#top'
    get    '/features'                          => 'articles#feature'
    get    '/future_events'                     => 'events#future'
    get    '/ongoing_events'                    => 'events#ongoing'
    get    '/latest_posts'                      => 'posts#latest'
    get    '/unreplied_posts'                   => 'posts#unreplied'

    # ios
    resources :articles, only: %i(index show) do
      get :top, on: :collection
    end
    resources :categories, only: %i(index) do
      get :articles, on: :member
    end
    resources :comments, only: %i(create destroy)
    resources :conversations, only: %i(index) do
      get :messages, on: :member
    end
    resources :events, except: %i(new edit)
    resources :feedbacks, only: %i(create)
    resources :follows, only: %i(create destroy)
    resources :interests, only: %i(create destroy)
    resources :items, only: %i(index show update)
    resources :likes, only: %i(create destroy)
    resources :messages, only: %i(index create)
    resources :notifications, only: %i(index)
    resources :posts, except: %i(new edit) do
      member do
        get :replies
        get :comments
      end
      get :unreplied, on: :collection
    end
    resources :replies, only: %i(create show update)
    resources :reports, only: %i(create)
    resources :shops, only: %i(index show update) do
      member do
        get :items
        get :events
        get :staffs
      end
    end
    resources :tags, only: %i(index) do
      get :articles, on: :member
    end
    resources :tops, only: %i(), path: '/' do
      collection do
        get  :check_version
        post :login
        post :sign_up
        post :facebook
        get  :token_reference
        get  :check_notifications
        get  :coupons
      end
    end
    resources :users, only: %i(show) do
      member do
        get :likes
        get :interests
        get :posts
        get :watches
        get :follows
        get :replies
        get :followers
      end
      collection do
        patch :profile
        patch :setting
        patch :email
        patch :password
      end
    end
    resources :watches, only: %i(create destroy)
  end

  namespace :dashboard, { format: 'json' } do
    resources :tops, only: %i(), path: '/' do
      collection do
        post :login
        get  :shop_stats
        get  :overall_stats
        get  :shop_staffs
        get  :shop_replies
      end
    end
  end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  # association
  has_many :conversation_users, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :notifications, class_name: :ConversationNotification, foreign_key: :generic_id, dependent: :destroy
  has_many :users, through: :conversation_users

  # scope
  scope :newest, -> { order(newest_time: :desc, id: :desc) }
  scope :api_pagination, ->(last_object) { 
    where('conversations.newest_time < ?', last_object.newest_time).
    where('conversations.id < ?', last_object.id) if last_object }
  scope :api_index, ->(last_object) { api_pagination(last_object).newest.
    limit(Settings.api_limit[:conversations]) }
  scope :web_index, ->(page) { newest.page(page).per(Settings.api_limit[:conversations]) }

  # validation
  validates :newest_time, presence: true

  class << self
    def search(user_id, destination_user_id)
      ( self.joins(:users).merge(User.where(id: user_id)) & self.joins(:users).merge(User.where(id: destination_user_id)) ).first
    end
  end

  def destination(current_user_id)
    users.id_except(current_user_id).first
  end

  def newest_text
    messages.recent.find_by(type: :UserMessage).try(:text) || 'NO MESSAGE'
  end

  def has_unread_message?(user_id)
    notifications.by_user_id(user_id).new_notifications.present?
  end
end

app/controllers/api/conversations_controller.rb
class Api::ConversationsController < Api::ApiController
  def index
    ConversationNotification.by_user_id(@current_user.id).unconfirmed.update_all(status: 1)
    @conversations = @current_user.conversations.api_index(last_conversation)
    render template: 'api/conversations/index'
  end

  def messages
    @conversation = Conversation.find_by(id: id_params[:id])
    if @conversation
      if @conversation.users.find_by(id: @current_user.id)
        @conversation.notifications.by_user_id(@current_user.id).update_all(status: 2)
        @messages = @conversation.messages.api_index(last_message)
        render template: 'api/messages/index'
      else
        render json: {message: 'メッセージの閲覧権限がありません'}, status: 401
      end
    else
      render json: {message: 'メッセージが見つかりません'}, status: 404
    end
  end

  private
  def last_conversation
    Conversation.find(last_params[:last_object_id]) if last_params[:last_object_id].present?
  end

  def last_message
    Message.find(last_params[:last_object_id]) if last_params[:last_object_id].present?
  end

  def id_params
    params.permit(:id)
  end

  def last_params
    params.permit(:last_object_id)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    ConversationNotification.by_user_id(current_user.id).unconfirmed.update_all(status: 1)
    @conversations = current_user.conversations.web_index(page_params[:page])
  end

  def new
    destination_user_id = new_params[:destination_user_id]
    conversation = Conversation.search(current_user.id, destination_user_id)
    if conversation
      redirect_to conversation_path(conversation)
    else
      destination = User.find(destination_user_id)
      reply = Reply.find_by(id: new_params[:reply_id])
      if valid_params?(destination, reply)
        @conversation = Conversation.new(newest_time: Time.now)
        @destination_user_id = destination_user_id
        @reply_id = new_params[:reply_id]
      else
        redirect_to root_path, alert: '不正なパラメーターです'
      end
    end
  end

  def show
    @conversation = Conversation.find_by(id: id_params[:id])
    if @conversation
      if @conversation.users.find_by(id: current_user.id)
        @conversation.notifications.by_user_id(current_user.id).update_all(status: 2)
        @messages = @conversation.messages.web_index(page_params[:page])
      else
        redirect_to root_path, alert: 'メッセージの閲覧権限がありません'
      end
    else
      redirect_to root_path, alert: 'メッセージが見つかりません'
    end
  end

  private
  def id_params
    params.permit(:id)
  end

  def new_params
    params.permit(:destination_user_id, :reply_id)
  end

  def page_params
    params.permit(:page)
  end

  def valid_params?(destination, reply)
    if reply
      destination.staff? && reply.user = destination
    else
      destination.customer?
    end
  end
end

app/views/conversations/_conversation.html.erb
<% if @conversations.present? %>
  <% @conversations.each do |conversation| %>
    <article class="p-article p-article-notification <%= "confirmed" unless conversation.has_unread_message?(current_user.id) %> u-paper-shadow-z1">
      <% if conversation.has_unread_message?(current_user.id) %>
        <span class="c-icon-unread u-float__left">未読</span>
      <% end %>
      <span class="c-notification-message-time u-text-align__right">
        <%= time_ago_in_words(conversation.newest_time) %>
      </span>
      <div class="p-article-owner">
        <%= link_to conversation_path(conversation), class: "c-user-name" do %>
          <% if current_user.staff? %>
            <%= image_tag(object_image(conversation.user), size: "44x44") %>
            <h4>
              <%= conversation.user.name %>
              <span><%= strip_tags(conversation.newest_text).truncate(30) %></span>
            </h4>
          <% else %>
            <%= image_tag(object_image(conversation.staff), size: "44x44") %>
            <h4>
              <%= conversation.shop.name %>
              <span><%= strip_tags(conversation.newest_text).truncate(30) %></span>
            </h4>
          <% end %>
        <% end %>
        <%= image_tag(object_image(conversation.reply), size: "44x44", class: "u-border-radius-8") %>
      </div>
    </article>
  <% end %>
<% else %>
  <h3>No Messages</h3>
<% end %>

app/views/conversations/index.html.erb
<section class="l-flex__center <%= 'has-header-tab' if current_user %>">

  <div id="notification-feed">
    <% if @conversations.present? %>
      <% @conversations.each do |conversation| %>
        <article class="p-article p-article-notification <%= "confirmed" unless conversation.has_unread_message?(current_user.id) %> u-paper-shadow-z1">
          <div class="p-article-owner">
            <%= link_to conversation_path(conversation), class: "c-user-name" do %>
              <% destination = conversation.destination(current_user.id) %>
              <%= image_tag(object_image(destination), size: "44x44") %>
              <h4>
                <% if conversation.has_unread_message?(current_user.id) %>
                  <p class="c-icon-new" style="font-size:13px;padding:2px 10px;margin-right:5px;">未読</p>
                <% end %>
                <%= destination.name %>
                <span><%= strip_tags(conversation.newest_text).truncate(30) %></span>
              </h4>
            <% end %>
            <span class="c-notification-message-time u-float__right">
              <p style="margin-bottom:3px;"><%= time_ago_in_words(conversation.newest_time) %></p>
            </span>
          </div>
        </article>
      <% end %>
    <% else %>
      <article class="p-article u-paper-shadow-z1">
        <p class="u-text-align__center">まだ Message がありません</p>
      </article>
    <% end %>
  </div>

  <%= form_tag conversations_path, method: "get", id: "pagination" do %>
    <%= link_to_next_page @conversations, "", remote: true %>
  <% end %>

</section>

app/views/conversations/index.js.erb
$("#conversation").html("<%= escape_javascript(render 'conversation', object: @conversations) %>");
$('#paginator').html('<%= escape_javascript(link_to_next_page @conversations, "さらに表示", remote: true) %>');

app/views/conversations/new.html.erb
<section class="l-flex__center">
  <article class="p-article u-paper-shadow-z1" style="background-color: #EEEEEE; padding: 5px 20px;">
    <% if current_user.customer? %>
      <p style="font-weight: bold;">下記についてよく聞かれます：</p>
      <p>1. 商品を活用したコーディネイトについて</p>
      <p>2. 商品の店頭での在庫について</p>
      <p>3. 来店予約について</p>
    <% else %>
      <p style="font-weight: bold;">フォローのお礼と一緒によく聞かれること：</p>
      <p>1. いま探しているアイテムについて</p>
      <p>2. 普段よく着る服のテイストについて</p>
      <p>3. 普段よく行くショップについて</p>
    <% end %>
  </article>
  <% if reply = Reply.find_by(id: @reply_id) %>
    <article class="p-article" style="position:relative;padding: 20px 20px 20px 120px;min-height:80px;border: 1px solid #D8D8D8;">
      <%= image_tag(object_image(reply), size: "80x80", style: "border-radius: 8px;position:absolute;top:20px;left:20px;") %>
      <span style="font-weight: bold;"><%= reply.item_name %></span><br>
      <span><%= reply.item_brand %></span></br>
      <span><%= number_to_currency(reply.item_price) %>（税込）</span>
    </article>
  <% end %>
  <article class="p-article u-paper-shadow-z1" style="padding:15px 25px;">
    <% placeholder = current_user.customer? ? "商品について何でも聞いてみよう！" : "メッセージを入力しましょう！" %>
    <%= form_tag(messages_path, remote: true, class: "c-form__comment-textarea") do %>
      <%= hidden_field_tag "destination_user_id", @destination_user_id %>
      <%= hidden_field_tag "reply_id", @reply_id %>
      <%= text_area_tag "text", "", rows: 1, placeholder: placeholder, class: "c-form__textarea-message", required: true %>
      <%= button_tag "送信", id: "sendmessage", style: 'margin-top:0px;', type: 'submit', class: "c-button__submit c-button__conversation-new", data: { disable_with: "送信" } %>
    <% end %>
  </article>
</section>

app/views/conversations/show.html.erb
<section class="l-flex__center">
  <article class="p-article p-article-message u-paper-shadow-z1" style="padding:15px 25px;">
    <div id="message-timeline">
      <% message_type = nil %>
      <% if @messages.present? %>
        <% @messages.reverse.each do |message| %>
          <div id="message_<%= message.id %>" class="<%= message.user === current_user ? 'p-article-messege__sender' : 'p-article-messege__recipient'%>">
            <% unless message_type == (message.user == current_user ? 'sender' : 'recipient') %>
              <div class="p-article-owner" style="margin-top:10px;margin-bottom:0px;">
                <%= link_to user_path(message.user), class: "c-user-name" do %>
                  <%= image_tag(object_image(message.user), size: "44x44") %>
                  <h4>
                    <%= message.user.name %>
                    <span><%= time_ago_in_words(message.created_at) %></span>
                  </h4>
                <% end %>
              </div>
            <% end %>
            <div class="p-article-desc" style="margin-top:10px;margin-bottom:0px;">
              <%= auto_link(change_br(message.text)) %>
            </div>
          </div>
          <% message_type = message.user == current_user ? 'sender' : 'recipient' %>
        <% end %>
      <% end %>
    </div>
  </article>

  <article class="p-article u-paper-shadow-z1" style="padding:15px 25px;">
    <%= form_tag(messages_path, remote: true, class: "c-form__comment-textarea") do %>
      <%= hidden_field_tag "conversation_id", @conversation.id %>
      <%= hidden_field_tag "destination_user_id", @conversation.destination(current_user.id).id %>
      <%= text_area_tag "text", "", rows: 1, placeholder: "商品について何でも聞いてみよう！", class: "c-form__textarea-message", required: true %>
      <%= button_tag "送信", style: 'margin-top:0px;', type: 'submit', class: "c-button__submit c-button__conversation-new", data: { disable_with: "送信" } %>
    <% end %>
  </article>

</section>