config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }
  devise_for :developers, controllers: {
    sessions: 'developers/sessions'
  }
  mount RailsAdmin::Engine => '/developer', as: 'rails_admin'

  # Publicページ
  get  '/', :to => redirect('/ios-app')
  get  '/', :to => redirect('/press')

  # 旧STYLER MAGからのリダイレクト処理
  get  '/wp_articles/:id'              => 'articles#wp_show'

  # 旧URLからのリダイレクト処理
  get  '/replys/:id'                   => 'replies#ex_show'

  resources :articles, only: %i(index show)
  resources :comments, only: %i(create destroy)
  resources :conversations, only: %i(index new show)
  resources :events
  resources :favorites, only: %i(create destroy)
  resources :feedbacks, only: %i(new create)
  resources :follows, only: %i(create destroy)
  resources :interests, only: %i(create destroy)
  resources :items
  resources :likes, only: %i(create destroy)
  resources :messages, only: %i(create)
  resources :notifications, only: %i(index)
  resources :posts do
    collection do
      get :latest
      get :unreplied
    end
  end
  resources :replies, except: %i(index destroy)
  get  '/replies/:id/embed'            => 'replies#embed', as: 'replies_embed'
  get  '/replies/:id/embed_link'       => 'replies#generate_embed_link', as: 'embed_link'
  resources :reports, only: %i(new create)
  resources :shops, except: %i(new create destroy) do
    member do
      get :items
      get :events
      get :staffs
      get :information
    end
  end
  resources :shop_registrations, only: %i(new create)
  resources :shop_users, only: %i(new create)
  resources :tops, only: %i(), path: '/' do
    collection do
      get :privacy_policy
      get :use_policy
      get :company
      get :help
      get :pending
    end
  end
  resources :users, only: %i(show edit update) do
    member do
      get :watches
      get :likes
      get :interests
      get :follows
      get :followers
    end
    collection do
      get :setting
      get :change_email
      get :mail_setting
    end
  end
  resources :watches, only: %i(create destroy)

  namespace :admin do
    resources :articles, only: %i(index edit update) do
      get :reload, on: :collection
    end
    resources :authors, only: %i(index edit update)
    resources :categories, only: %i(index new create)
    resources :contacts, only: %i(index new create)
    resources :kpis, only: %i(index)
    resources :html_mails, only: %i(index) do
      collection do
        get :welcome_mail
        get :comment_mail
        get :feedback_mail
        get :message_mail
        get :reply_mail
        get :start_events_mail
        get :approval_mail
        get :staff_invite_mail
      end
    end
    resources :push_notifications, only: %i(new create)
    resources :reports, only: %i(index update)
    resources :shops, only: %i(index new create update)
    resources :shop_registrations, only: %i(index show update)
    resources :tops, only: %i(index)
    resources :users, only: %i(index new create)
  end

  namespace :api, { format: 'json' } do
    # KPI
    get    '/kpi'                               => 'tops#kpi'

    # 削除予定
    get    '/articles_top'                      => 'articles#top'
    get    '/features'                          => 'articles#feature'
    get    '/future_events'                     => 'events#future'
    get    '/ongoing_events'                    => 'events#ongoing'
    get    '/latest_posts'                      => 'posts#latest'
    get    '/unreplied_posts'                   => 'posts#unreplied'

    # ios
    resources :articles, only: %i(index show) do
      get :top, on: :collection
    end
    resources :categories, only: %i(index) do
      get :articles, on: :member
    end
    resources :comments, only: %i(create destroy)
    resources :conversations, only: %i(index) do
      get :messages, on: :member
    end
    resources :events, except: %i(new edit)
    resources :feedbacks, only: %i(create)
    resources :follows, only: %i(create destroy)
    resources :interests, only: %i(create destroy)
    resources :items, only: %i(index show update)
    resources :likes, only: %i(create destroy)
    resources :messages, only: %i(index create)
    resources :notifications, only: %i(index)
    resources :posts, except: %i(new edit) do
      member do
        get :replies
        get :comments
      end
      get :unreplied, on: :collection
    end
    resources :replies, only: %i(create show update)
    resources :reports, only: %i(create)
    resources :shops, only: %i(index show update) do
      member do
        get :items
        get :events
        get :staffs
      end
    end
    resources :tags, only: %i(index) do
      get :articles, on: :member
    end
    resources :tops, only: %i(), path: '/' do
      collection do
        get  :check_version
        post :login
        post :sign_up
        post :facebook
        get  :token_reference
        get  :check_notifications
        get  :coupons
      end
    end
    resources :users, only: %i(show) do
      member do
        get :likes
        get :interests
        get :posts
        get :watches
        get :follows
        get :replies
        get :followers
      end
      collection do
        patch :profile
        patch :setting
        patch :email
        patch :password
      end
    end
    resources :watches, only: %i(create destroy)
  end

  namespace :dashboard, { format: 'json' } do
    resources :tops, only: %i(), path: '/' do
      collection do
        post :login
        get  :shop_stats
        get  :overall_stats
        get  :shop_staffs
        get  :shop_replies
      end
    end
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  # association
  belongs_to :user

  # enum
  enum status: { unconfirmed: 0, browsed: 1, confirmed: 2 }

  # scope
  scope :recent, -> { order(created_at: :desc, id: :desc) }
  scope :by_user_id, ->(user_id) { where(user_id: user_id) }
  scope :timeline, -> { where.not(type: :ConversationNotification) }
  scope :new_notifications, -> { where.not(status: 2) }
  scope :api_pagination, ->(last_object) { 
    where('notifications.created_at <= ?', last_object.created_at).
    where('notifications.id < ?', last_object.id) if last_object }
  scope :api_index, ->(last_object) { includes(:notification_object).includes(notification_author: :image).api_pagination(last_object).timeline.recent.limit(Settings.api_limit[:notifications]) }
  scope :web_index, ->(page) { includes(:notification_object).includes(notification_author: :image).timeline.recent.page(page).per(Settings.api_limit[:notifications]) }

  # validation
  validates :user_id, :generic_id, :type, presence: true
  validates :user_id, uniqueness: { scope: [:generic_id, :type] }

  class << self
    def browse!(user_id)
      by_user_id(user_id).new_notifications.each do |notification|
        notification.confirmed! if notification.browsed?
        notification.browsed! if notification.unconfirmed?
      end
    end
  end
end

app/controllers/api/notifications_controller.rb
class Api::NotificationsController < Api::ApiController
  def index
    Notification.browse!(@current_user.id)
    @notifications = @current_user.notifications.api_index(last_notification)
    render template: 'api/notifications/index'
  end

  private
  def last_notification
    Notification.find(last_params[:last_object_id]) if last_params[:last_object_id].present?
  end

  def last_params
    params.permit(:last_object_id)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    if conversation_tab?
      redirect_to conversations_path
    else
      Notification.browse!(current_user.id)
      @notifications = current_user.notifications.web_index(page_params[:page])
    end
  end

  private
  def conversation_tab?
    current_user.notifications.unconfirmed.where.not(type: 'ConversationNotification').blank? && current_user.notifications.unconfirmed.where(type: 'ConversationNotification').present?
  end

  def page_params
    params.permit(:page)
  end
end

app/views/notifications/_notification.html.erb
<% if @notifications.present? %>
  <% @notifications.each do |notification| %>

    <% case notification.type %>
    <% when "ReplyNotification" %>
      <article class="p-article p-article-notification <%= confirmed?(notification) %> u-paper-shadow-z1">
        <div class="p-article-owner">
          <%= link_to user_path(notification.reply.user), class: "c-user-name" do %>
            <%= image_tag(object_image(notification.reply.user), size: "32x32") %>
            <h4>
              <%= notification.reply.user.name %>
              <span><%= time_ago_in_words(notification.created_at) %></span>
            </h4>
          <% end %>
        </div>
        <div class="p-article-desc">
          <p>
            <% if notification.reply.post.user_id == current_user.id %>
              あなたのPostにReplyしました
            <% else %>
              あなたがWatchしているPostにReplyしました
            <% end %>
          </p>
        </div>
        <%= link_to reply_path(notification.reply, anchor: "reply"), class: "p-article-notification-item" do %>
          <span><%= strip_tags(notification.reply.comment).truncate(40) %></span>
          <%= image_tag(object_image(notification.reply), size: "70x70") %>
        <% end %>
      </article>

    <% when "CommentNotification" %>
      <article class="p-article p-article-notification <%= confirmed?(notification) %> u-paper-shadow-z1">
        <div class="p-article-owner">
          <%= link_to user_path(notification.comment.user), class: "c-user-name" do %>
            <%= image_tag(object_image(notification.comment.user), size: "32x32") %>
            <h4>
              <%= notification.comment.user.name %>
              <span><%= time_ago_in_words(notification.created_at) %></span>
            </h4>
          <% end %>
        </div>
        <div class="p-article-desc">
          <p>あなたのPostにコメントを投稿しました</p>
        </div>
        <%= link_to post_path(notification.comment.post, anchor: "comment_#{notification.comment.id}"), class: "p-article-notification-item", data: { no_turbolink: true } do %>
          <span><%= strip_tags(notification.comment.text).truncate(40) %></span>
          <i class="c-icon-comment"></i>
        <% end %>
      </article>

    <% when "LikeNotification" %>
      <article class="p-article p-article-notification <%= confirmed?(notification) %> u-paper-shadow-z1">
        <div class="p-article-owner">
          <%= link_to user_path(notification.like.user), class: "c-user-name" do %>
            <%= image_tag(object_image(notification.like.user), size: "32x32") %>
            <h4>
              <%= notification.like.user.name %>
              <span><%= time_ago_in_words(notification.created_at) %></span>
            </h4>
          <% end %>
        </div>
        <div class="p-article-desc">
          <p>あなたのコメントにLikeしました</p>
        </div>
        <%= link_to post_path(notification.like.comment.post, anchor: "comment_#{notification.like.comment.id}"), class: "p-article-notification-item", data: { no_turbolink: true } do %>
          <span><%= strip_tags(notification.like.comment.text).truncate(40) %></span>
          <i class="c-icon-like"></i>
        <% end %>
      </article>

    <% when "EventNotification" %>
      <article class="p-article p-article-notification <%= confirmed?(notification) %> u-paper-shadow-z1">
        <div class="p-article-owner">
          <%= link_to shop_path(notification.event.shop), class: "c-user-name" do %>
            <%= image_tag(object_image(notification.event.shop), size: "32x32") %>
            <h4>
              <%= notification.event.shop.name %>
              <span><%= time_ago_in_words(notification.created_at) %></span>
            </h4>
          <% end %>
        </div>
        <div class="p-article-desc">
          <p>新しいイベントを公開しました</p>
        </div>
        <%= link_to event_path(notification.event), class: "p-article-notification-item" do %>
          <span><%= strip_tags(notification.event.text).truncate(40) %></span>
          <%= image_tag(object_image(notification.event), size: "70x70") %>
        <% end %>
      </article>

    <% when "InterestNotification" %>
      <article class="p-article p-article-notification <%= confirmed?(notification) %> u-paper-shadow-z1">
        <div class="p-article-owner">
          <%= link_to user_path(notification.interest.user), class: "c-user-name" do %>
            <%= image_tag(object_image(notification.interest.user), size: "32x32") %>
            <h4>
              <%= notification.interest.user.name %>
              <span><%= time_ago_in_words(notification.created_at) %></span>
            </h4>
          <% end %>
        </div>
        <div class="p-article-desc">
          <p>あなたのShopのイベントにInterestしました</p>
        </div>
        <%= link_to event_path(notification.interest.event), class: "p-article-notification-item" do %>
          <span><%= strip_tags(notification.interest.event.text).truncate(40) %></span>
          <%= image_tag(object_image(notification.interest.event), size: "70x70") %>
        <% end %>
      </article>

    <% when "FollowNotification" %>
      <article class="p-article p-article-notification <%= confirmed?(notification) %> u-paper-shadow-z1">
        <div class="p-article-owner">
          <%= link_to user_path(notification.follow.user), class: "c-user-name" do %>
            <%= image_tag(object_image(notification.follow.user), size: "32x32") %>
            <h4>
              <%= notification.follow.user.name %>
              <span><%= time_ago_in_words(notification.created_at) %></span>
            </h4>
          <% end %>
        </div>
        <div class="p-article-desc">
          <p>あなたをFollowしました</p>
        </div>
      </article>
    <% end %>
  <% end %>
<% else %>
  <article class="p-article u-paper-shadow-z1">
    <p class="u-text-align__center">まだ Activity がありません</p>
  </article>
<% end %>

app/views/notifications/_tab.html.erb
<div class="p-header-tab">
  <%= link_to "Activity", notifications_path, class: "c-header-tab #{'is-current' if check_route('notifications', 'index')}" %>
  <%= link_to "Message", conversations_path, class: "c-header-tab #{'is-current' if check_route('conversations', 'index')}" %>
</div>

app/views/notifications/index.html.erb
<section class="l-flex__center <%= 'has-header-tab' if current_user %>">

  <div id="notification-feed">
    <%= render "notification" %>
  </div>

  <%= form_tag notifications_path, method: "get", id: "pagination" do %>
    <%= link_to_next_page @notifications, "", remote: true %>
  <% end %>

</section>

app/views/notifications/index.js.erb
<% if params[:ajax_handler] == "activity" %>
$ ("#notification").html("<%= escape_javascript(render 'notification', object: @notifications) %>");
  $('#paginator').html('<%= escape_javascript(render "pagination", object: @notifications) %>');
<% elsif params[:ajax_handler] == "message" %>
  $("#notification").html("<%= escape_javascript(render partial: 'conversations/conversation', object: @conversations) %>");
  $('#paginator').html('<%= escape_javascript(render partial: "conversations/pagination", object: @conversations) %>');
<% else %>
  $("#notification").html("<%= escape_javascript(render 'notification', object: @notifications) %>");
  $('#paginator').html('<%= escape_javascript(render "pagination", object: @notifications) %>');
<% end %>